// proto/service.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: proto/service.proto

package crud

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age  int32  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type CreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReadAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadAllRequest) Reset() {
	*x = ReadAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllRequest) ProtoMessage() {}

func (x *ReadAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllRequest.ProtoReflect.Descriptor instead.
func (*ReadAllRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{2}
}

type ReadAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Responses []*ResponseRead `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
}

func (x *ReadAllResponse) Reset() {
	*x = ReadAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllResponse) ProtoMessage() {}

func (x *ReadAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllResponse.ProtoReflect.Descriptor instead.
func (*ReadAllResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReadAllResponse) GetResponses() []*ResponseRead {
	if x != nil {
		return x.Responses
	}
	return nil
}

type ResponseRead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NamaBarang   string `protobuf:"bytes,1,opt,name=nama_barang,json=namaBarang,proto3" json:"nama_barang,omitempty"`
	FotoBarang   string `protobuf:"bytes,2,opt,name=foto_barang,json=fotoBarang,proto3" json:"foto_barang,omitempty"`
	Harga        int32  `protobuf:"varint,3,opt,name=harga,proto3" json:"harga,omitempty"`
	NamaKategori string `protobuf:"bytes,4,opt,name=nama_kategori,json=namaKategori,proto3" json:"nama_kategori,omitempty"`
	NamaJenis    string `protobuf:"bytes,5,opt,name=nama_jenis,json=namaJenis,proto3" json:"nama_jenis,omitempty"`
	NoBatch      string `protobuf:"bytes,6,opt,name=no_batch,json=noBatch,proto3" json:"no_batch,omitempty"`
}

func (x *ResponseRead) Reset() {
	*x = ResponseRead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseRead) ProtoMessage() {}

func (x *ResponseRead) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseRead.ProtoReflect.Descriptor instead.
func (*ResponseRead) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{4}
}

func (x *ResponseRead) GetNamaBarang() string {
	if x != nil {
		return x.NamaBarang
	}
	return ""
}

func (x *ResponseRead) GetFotoBarang() string {
	if x != nil {
		return x.FotoBarang
	}
	return ""
}

func (x *ResponseRead) GetHarga() int32 {
	if x != nil {
		return x.Harga
	}
	return 0
}

func (x *ResponseRead) GetNamaKategori() string {
	if x != nil {
		return x.NamaKategori
	}
	return ""
}

func (x *ResponseRead) GetNamaJenis() string {
	if x != nil {
		return x.NamaJenis
	}
	return ""
}

func (x *ResponseRead) GetNoBatch() string {
	if x != nil {
		return x.NoBatch
	}
	return ""
}

type ReadWithCategoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadWithCategoryRequest) Reset() {
	*x = ReadWithCategoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadWithCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadWithCategoryRequest) ProtoMessage() {}

func (x *ReadWithCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadWithCategoryRequest.ProtoReflect.Descriptor instead.
func (*ReadWithCategoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{5}
}

type ReadWithCategoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Responses []*ResponseReadCategory `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
}

func (x *ReadWithCategoryResponse) Reset() {
	*x = ReadWithCategoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadWithCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadWithCategoryResponse) ProtoMessage() {}

func (x *ReadWithCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadWithCategoryResponse.ProtoReflect.Descriptor instead.
func (*ReadWithCategoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{6}
}

func (x *ReadWithCategoryResponse) GetResponses() []*ResponseReadCategory {
	if x != nil {
		return x.Responses
	}
	return nil
}

type ResponseReadCategory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NamaBarang   string `protobuf:"bytes,1,opt,name=nama_barang,json=namaBarang,proto3" json:"nama_barang,omitempty"`
	FotoBarang   string `protobuf:"bytes,2,opt,name=foto_barang,json=fotoBarang,proto3" json:"foto_barang,omitempty"`
	Harga        int32  `protobuf:"varint,3,opt,name=harga,proto3" json:"harga,omitempty"`
	NamaKategori string `protobuf:"bytes,4,opt,name=nama_kategori,json=namaKategori,proto3" json:"nama_kategori,omitempty"`
}

func (x *ResponseReadCategory) Reset() {
	*x = ResponseReadCategory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseReadCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseReadCategory) ProtoMessage() {}

func (x *ResponseReadCategory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseReadCategory.ProtoReflect.Descriptor instead.
func (*ResponseReadCategory) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{7}
}

func (x *ResponseReadCategory) GetNamaBarang() string {
	if x != nil {
		return x.NamaBarang
	}
	return ""
}

func (x *ResponseReadCategory) GetFotoBarang() string {
	if x != nil {
		return x.FotoBarang
	}
	return ""
}

func (x *ResponseReadCategory) GetHarga() int32 {
	if x != nil {
		return x.Harga
	}
	return 0
}

func (x *ResponseReadCategory) GetNamaKategori() string {
	if x != nil {
		return x.NamaKategori
	}
	return ""
}

type ReadWithJenisRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadWithJenisRequest) Reset() {
	*x = ReadWithJenisRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadWithJenisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadWithJenisRequest) ProtoMessage() {}

func (x *ReadWithJenisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadWithJenisRequest.ProtoReflect.Descriptor instead.
func (*ReadWithJenisRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{8}
}

type ReadWithJenisResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Responses []*ResponseReadJenis `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
}

func (x *ReadWithJenisResponse) Reset() {
	*x = ReadWithJenisResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadWithJenisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadWithJenisResponse) ProtoMessage() {}

func (x *ReadWithJenisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadWithJenisResponse.ProtoReflect.Descriptor instead.
func (*ReadWithJenisResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{9}
}

func (x *ReadWithJenisResponse) GetResponses() []*ResponseReadJenis {
	if x != nil {
		return x.Responses
	}
	return nil
}

type ResponseReadJenis struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NamaBarang string `protobuf:"bytes,1,opt,name=nama_barang,json=namaBarang,proto3" json:"nama_barang,omitempty"`
	FotoBarang string `protobuf:"bytes,2,opt,name=foto_barang,json=fotoBarang,proto3" json:"foto_barang,omitempty"`
	Harga      int32  `protobuf:"varint,3,opt,name=harga,proto3" json:"harga,omitempty"`
	NamaJenis  string `protobuf:"bytes,4,opt,name=nama_jenis,json=namaJenis,proto3" json:"nama_jenis,omitempty"`
}

func (x *ResponseReadJenis) Reset() {
	*x = ResponseReadJenis{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseReadJenis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseReadJenis) ProtoMessage() {}

func (x *ResponseReadJenis) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseReadJenis.ProtoReflect.Descriptor instead.
func (*ResponseReadJenis) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{10}
}

func (x *ResponseReadJenis) GetNamaBarang() string {
	if x != nil {
		return x.NamaBarang
	}
	return ""
}

func (x *ResponseReadJenis) GetFotoBarang() string {
	if x != nil {
		return x.FotoBarang
	}
	return ""
}

func (x *ResponseReadJenis) GetHarga() int32 {
	if x != nil {
		return x.Harga
	}
	return 0
}

func (x *ResponseReadJenis) GetNamaJenis() string {
	if x != nil {
		return x.NamaJenis
	}
	return ""
}

type ReadWithMaterialRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadWithMaterialRequest) Reset() {
	*x = ReadWithMaterialRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadWithMaterialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadWithMaterialRequest) ProtoMessage() {}

func (x *ReadWithMaterialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadWithMaterialRequest.ProtoReflect.Descriptor instead.
func (*ReadWithMaterialRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{11}
}

type ReadWithMaterialResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Responses []*ResponseReadMaterial `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
}

func (x *ReadWithMaterialResponse) Reset() {
	*x = ReadWithMaterialResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadWithMaterialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadWithMaterialResponse) ProtoMessage() {}

func (x *ReadWithMaterialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadWithMaterialResponse.ProtoReflect.Descriptor instead.
func (*ReadWithMaterialResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{12}
}

func (x *ReadWithMaterialResponse) GetResponses() []*ResponseReadMaterial {
	if x != nil {
		return x.Responses
	}
	return nil
}

type ResponseReadMaterial struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NamaBarang   string `protobuf:"bytes,1,opt,name=nama_barang,json=namaBarang,proto3" json:"nama_barang,omitempty"`
	FotoBarang   string `protobuf:"bytes,2,opt,name=foto_barang,json=fotoBarang,proto3" json:"foto_barang,omitempty"`
	Harga        int32  `protobuf:"varint,3,opt,name=harga,proto3" json:"harga,omitempty"`
	NamaMaterial string `protobuf:"bytes,4,opt,name=nama_material,json=namaMaterial,proto3" json:"nama_material,omitempty"`
}

func (x *ResponseReadMaterial) Reset() {
	*x = ResponseReadMaterial{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseReadMaterial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseReadMaterial) ProtoMessage() {}

func (x *ResponseReadMaterial) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseReadMaterial.ProtoReflect.Descriptor instead.
func (*ResponseReadMaterial) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{13}
}

func (x *ResponseReadMaterial) GetNamaBarang() string {
	if x != nil {
		return x.NamaBarang
	}
	return ""
}

func (x *ResponseReadMaterial) GetFotoBarang() string {
	if x != nil {
		return x.FotoBarang
	}
	return ""
}

func (x *ResponseReadMaterial) GetHarga() int32 {
	if x != nil {
		return x.Harga
	}
	return 0
}

func (x *ResponseReadMaterial) GetNamaMaterial() string {
	if x != nil {
		return x.NamaMaterial
	}
	return ""
}

type ReadWithBatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadWithBatchRequest) Reset() {
	*x = ReadWithBatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadWithBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadWithBatchRequest) ProtoMessage() {}

func (x *ReadWithBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadWithBatchRequest.ProtoReflect.Descriptor instead.
func (*ReadWithBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{14}
}

type ReadWithBatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Responses []*ResponseReadBatch `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
}

func (x *ReadWithBatchResponse) Reset() {
	*x = ReadWithBatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadWithBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadWithBatchResponse) ProtoMessage() {}

func (x *ReadWithBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadWithBatchResponse.ProtoReflect.Descriptor instead.
func (*ReadWithBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{15}
}

func (x *ReadWithBatchResponse) GetResponses() []*ResponseReadBatch {
	if x != nil {
		return x.Responses
	}
	return nil
}

type ResponseReadBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NamaBarang string `protobuf:"bytes,1,opt,name=nama_barang,json=namaBarang,proto3" json:"nama_barang,omitempty"`
	FotoBarang string `protobuf:"bytes,2,opt,name=foto_barang,json=fotoBarang,proto3" json:"foto_barang,omitempty"`
	Harga      int32  `protobuf:"varint,3,opt,name=harga,proto3" json:"harga,omitempty"`
	NomorBatch string `protobuf:"bytes,4,opt,name=nomor_batch,json=nomorBatch,proto3" json:"nomor_batch,omitempty"`
}

func (x *ResponseReadBatch) Reset() {
	*x = ResponseReadBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseReadBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseReadBatch) ProtoMessage() {}

func (x *ResponseReadBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseReadBatch.ProtoReflect.Descriptor instead.
func (*ResponseReadBatch) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{16}
}

func (x *ResponseReadBatch) GetNamaBarang() string {
	if x != nil {
		return x.NamaBarang
	}
	return ""
}

func (x *ResponseReadBatch) GetFotoBarang() string {
	if x != nil {
		return x.FotoBarang
	}
	return ""
}

func (x *ResponseReadBatch) GetHarga() int32 {
	if x != nil {
		return x.Harga
	}
	return 0
}

func (x *ResponseReadBatch) GetNomorBatch() string {
	if x != nil {
		return x.NomorBatch
	}
	return ""
}

type ReadNotExpiredBarangRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadNotExpiredBarangRequest) Reset() {
	*x = ReadNotExpiredBarangRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadNotExpiredBarangRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadNotExpiredBarangRequest) ProtoMessage() {}

func (x *ReadNotExpiredBarangRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadNotExpiredBarangRequest.ProtoReflect.Descriptor instead.
func (*ReadNotExpiredBarangRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{17}
}

type ReadNotExpiredBarangResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Responses []*ResponseReadNotExpired `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
}

func (x *ReadNotExpiredBarangResponse) Reset() {
	*x = ReadNotExpiredBarangResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadNotExpiredBarangResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadNotExpiredBarangResponse) ProtoMessage() {}

func (x *ReadNotExpiredBarangResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadNotExpiredBarangResponse.ProtoReflect.Descriptor instead.
func (*ReadNotExpiredBarangResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{18}
}

func (x *ReadNotExpiredBarangResponse) GetResponses() []*ResponseReadNotExpired {
	if x != nil {
		return x.Responses
	}
	return nil
}

type ResponseReadNotExpired struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NamaBarang string `protobuf:"bytes,1,opt,name=nama_barang,json=namaBarang,proto3" json:"nama_barang,omitempty"`
	NomorBatch string `protobuf:"bytes,2,opt,name=nomor_batch,json=nomorBatch,proto3" json:"nomor_batch,omitempty"`
	Stok       int32  `protobuf:"varint,3,opt,name=stok,proto3" json:"stok,omitempty"`
	TglExpired string `protobuf:"bytes,4,opt,name=tgl_expired,json=tglExpired,proto3" json:"tgl_expired,omitempty"`
}

func (x *ResponseReadNotExpired) Reset() {
	*x = ResponseReadNotExpired{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseReadNotExpired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseReadNotExpired) ProtoMessage() {}

func (x *ResponseReadNotExpired) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseReadNotExpired.ProtoReflect.Descriptor instead.
func (*ResponseReadNotExpired) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{19}
}

func (x *ResponseReadNotExpired) GetNamaBarang() string {
	if x != nil {
		return x.NamaBarang
	}
	return ""
}

func (x *ResponseReadNotExpired) GetNomorBatch() string {
	if x != nil {
		return x.NomorBatch
	}
	return ""
}

func (x *ResponseReadNotExpired) GetStok() int32 {
	if x != nil {
		return x.Stok
	}
	return 0
}

func (x *ResponseReadNotExpired) GetTglExpired() string {
	if x != nil {
		return x.TglExpired
	}
	return ""
}

type ReadExpiredBarangRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadExpiredBarangRequest) Reset() {
	*x = ReadExpiredBarangRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadExpiredBarangRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadExpiredBarangRequest) ProtoMessage() {}

func (x *ReadExpiredBarangRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadExpiredBarangRequest.ProtoReflect.Descriptor instead.
func (*ReadExpiredBarangRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{20}
}

type ReadExpiredBarangResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Responses []*ResponseReadExpired `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
}

func (x *ReadExpiredBarangResponse) Reset() {
	*x = ReadExpiredBarangResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadExpiredBarangResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadExpiredBarangResponse) ProtoMessage() {}

func (x *ReadExpiredBarangResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadExpiredBarangResponse.ProtoReflect.Descriptor instead.
func (*ReadExpiredBarangResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{21}
}

func (x *ReadExpiredBarangResponse) GetResponses() []*ResponseReadExpired {
	if x != nil {
		return x.Responses
	}
	return nil
}

type ResponseReadExpired struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NamaBarang string `protobuf:"bytes,1,opt,name=nama_barang,json=namaBarang,proto3" json:"nama_barang,omitempty"`
	NomorBatch string `protobuf:"bytes,2,opt,name=nomor_batch,json=nomorBatch,proto3" json:"nomor_batch,omitempty"`
	Stok       int32  `protobuf:"varint,3,opt,name=stok,proto3" json:"stok,omitempty"`
	TglExpired string `protobuf:"bytes,4,opt,name=tgl_expired,json=tglExpired,proto3" json:"tgl_expired,omitempty"`
}

func (x *ResponseReadExpired) Reset() {
	*x = ResponseReadExpired{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseReadExpired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseReadExpired) ProtoMessage() {}

func (x *ResponseReadExpired) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseReadExpired.ProtoReflect.Descriptor instead.
func (*ResponseReadExpired) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{22}
}

func (x *ResponseReadExpired) GetNamaBarang() string {
	if x != nil {
		return x.NamaBarang
	}
	return ""
}

func (x *ResponseReadExpired) GetNomorBatch() string {
	if x != nil {
		return x.NomorBatch
	}
	return ""
}

func (x *ResponseReadExpired) GetStok() int32 {
	if x != nil {
		return x.Stok
	}
	return 0
}

func (x *ResponseReadExpired) GetTglExpired() string {
	if x != nil {
		return x.TglExpired
	}
	return ""
}

type UpdateHargaBatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Harga      int32  `protobuf:"varint,1,opt,name=harga,proto3" json:"harga,omitempty"`
	NomorBatch string `protobuf:"bytes,2,opt,name=nomor_batch,json=nomorBatch,proto3" json:"nomor_batch,omitempty"`
}

func (x *UpdateHargaBatchRequest) Reset() {
	*x = UpdateHargaBatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateHargaBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHargaBatchRequest) ProtoMessage() {}

func (x *UpdateHargaBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHargaBatchRequest.ProtoReflect.Descriptor instead.
func (*UpdateHargaBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateHargaBatchRequest) GetHarga() int32 {
	if x != nil {
		return x.Harga
	}
	return 0
}

func (x *UpdateHargaBatchRequest) GetNomorBatch() string {
	if x != nil {
		return x.NomorBatch
	}
	return ""
}

type UpdateHargaBatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UpdateHargaBatchResponse) Reset() {
	*x = UpdateHargaBatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateHargaBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHargaBatchResponse) ProtoMessage() {}

func (x *UpdateHargaBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHargaBatchResponse.ProtoReflect.Descriptor instead.
func (*UpdateHargaBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateHargaBatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateHargaBatchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateBulkRefRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*CreateBulkRef `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateBulkRefRequest) Reset() {
	*x = CreateBulkRefRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBulkRefRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBulkRefRequest) ProtoMessage() {}

func (x *CreateBulkRefRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBulkRefRequest.ProtoReflect.Descriptor instead.
func (*CreateBulkRefRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{25}
}

func (x *CreateBulkRefRequest) GetData() []*CreateBulkRef {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateBulkRefResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreateBulkRefResponse) Reset() {
	*x = CreateBulkRefResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBulkRefResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBulkRefResponse) ProtoMessage() {}

func (x *CreateBulkRefResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBulkRefResponse.ProtoReflect.Descriptor instead.
func (*CreateBulkRefResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{26}
}

func (x *CreateBulkRefResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateBulkRefResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateBulkRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdBarang string `protobuf:"bytes,1,opt,name=id_barang,json=idBarang,proto3" json:"id_barang,omitempty"`
	Stok     string `protobuf:"bytes,2,opt,name=stok,proto3" json:"stok,omitempty"`
	ExpDate  string `protobuf:"bytes,3,opt,name=exp_date,json=expDate,proto3" json:"exp_date,omitempty"`
	NoBatch  string `protobuf:"bytes,4,opt,name=no_batch,json=noBatch,proto3" json:"no_batch,omitempty"`
}

func (x *CreateBulkRef) Reset() {
	*x = CreateBulkRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBulkRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBulkRef) ProtoMessage() {}

func (x *CreateBulkRef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBulkRef.ProtoReflect.Descriptor instead.
func (*CreateBulkRef) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{27}
}

func (x *CreateBulkRef) GetIdBarang() string {
	if x != nil {
		return x.IdBarang
	}
	return ""
}

func (x *CreateBulkRef) GetStok() string {
	if x != nil {
		return x.Stok
	}
	return ""
}

func (x *CreateBulkRef) GetExpDate() string {
	if x != nil {
		return x.ExpDate
	}
	return ""
}

func (x *CreateBulkRef) GetNoBatch() string {
	if x != nil {
		return x.NoBatch
	}
	return ""
}

var File_proto_service_proto protoreflect.FileDescriptor

var file_proto_service_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x72, 0x75, 0x64, 0x22, 0x35, 0x0a, 0x0d, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61,
	0x67, 0x65, 0x22, 0x44, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x52, 0x65, 0x61, 0x64,
	0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x43, 0x0a, 0x0f, 0x52, 0x65,
	0x61, 0x64, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a,
	0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x63, 0x72, 0x75, 0x64, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x65, 0x61, 0x64, 0x52, 0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x22,
	0xc5, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x61, 0x64,
	0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x61, 0x6d, 0x61, 0x5f, 0x62, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x61, 0x6d, 0x61, 0x42, 0x61, 0x72, 0x61, 0x6e,
	0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x6f, 0x74, 0x6f, 0x5f, 0x62, 0x61, 0x72, 0x61, 0x6e, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x6f, 0x74, 0x6f, 0x42, 0x61, 0x72, 0x61,
	0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x61, 0x72, 0x67, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x68, 0x61, 0x72, 0x67, 0x61, 0x12, 0x23, 0x0a, 0x0d, 0x6e, 0x61, 0x6d, 0x61,
	0x5f, 0x6b, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x6e, 0x61, 0x6d, 0x61, 0x4b, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x12, 0x1d, 0x0a,
	0x0a, 0x6e, 0x61, 0x6d, 0x61, 0x5f, 0x6a, 0x65, 0x6e, 0x69, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x61, 0x4a, 0x65, 0x6e, 0x69, 0x73, 0x12, 0x19, 0x0a, 0x08,
	0x6e, 0x6f, 0x5f, 0x62, 0x61, 0x74, 0x63, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6e, 0x6f, 0x42, 0x61, 0x74, 0x63, 0x68, 0x22, 0x19, 0x0a, 0x17, 0x52, 0x65, 0x61, 0x64, 0x57,
	0x69, 0x74, 0x68, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x54, 0x0a, 0x18, 0x52, 0x65, 0x61, 0x64, 0x57, 0x69, 0x74, 0x68, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38,
	0x0a, 0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x72, 0x75, 0x64, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x52, 0x65, 0x61, 0x64, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x09, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x22, 0x93, 0x01, 0x0a, 0x14, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x61, 0x64, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x61, 0x6d, 0x61, 0x5f, 0x62, 0x61, 0x72, 0x61, 0x6e, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x61, 0x6d, 0x61, 0x42, 0x61, 0x72, 0x61,
	0x6e, 0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x6f, 0x74, 0x6f, 0x5f, 0x62, 0x61, 0x72, 0x61, 0x6e,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x6f, 0x74, 0x6f, 0x42, 0x61, 0x72,
	0x61, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x61, 0x72, 0x67, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x68, 0x61, 0x72, 0x67, 0x61, 0x12, 0x23, 0x0a, 0x0d, 0x6e, 0x61, 0x6d,
	0x61, 0x5f, 0x6b, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x6e, 0x61, 0x6d, 0x61, 0x4b, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x22, 0x16,
	0x0a, 0x14, 0x52, 0x65, 0x61, 0x64, 0x57, 0x69, 0x74, 0x68, 0x4a, 0x65, 0x6e, 0x69, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4e, 0x0a, 0x15, 0x52, 0x65, 0x61, 0x64, 0x57, 0x69,
	0x74, 0x68, 0x4a, 0x65, 0x6e, 0x69, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x35, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x72, 0x75, 0x64, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x52, 0x65, 0x61, 0x64, 0x4a, 0x65, 0x6e, 0x69, 0x73, 0x52, 0x09, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x22, 0x8a, 0x01, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x65, 0x61, 0x64, 0x4a, 0x65, 0x6e, 0x69, 0x73, 0x12, 0x1f, 0x0a, 0x0b,
	0x6e, 0x61, 0x6d, 0x61, 0x5f, 0x62, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x6e, 0x61, 0x6d, 0x61, 0x42, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x12, 0x1f, 0x0a,
	0x0b, 0x66, 0x6f, 0x74, 0x6f, 0x5f, 0x62, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x66, 0x6f, 0x74, 0x6f, 0x42, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x12, 0x14,
	0x0a, 0x05, 0x68, 0x61, 0x72, 0x67, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x68,
	0x61, 0x72, 0x67, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x61, 0x6d, 0x61, 0x5f, 0x6a, 0x65, 0x6e,
	0x69, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x61, 0x4a, 0x65,
	0x6e, 0x69, 0x73, 0x22, 0x19, 0x0a, 0x17, 0x52, 0x65, 0x61, 0x64, 0x57, 0x69, 0x74, 0x68, 0x4d,
	0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x54,
	0x0a, 0x18, 0x52, 0x65, 0x61, 0x64, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x63, 0x72, 0x75, 0x64, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x61,
	0x64, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x09, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x73, 0x22, 0x93, 0x01, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x1f, 0x0a,
	0x0b, 0x6e, 0x61, 0x6d, 0x61, 0x5f, 0x62, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x6e, 0x61, 0x6d, 0x61, 0x42, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x12, 0x1f,
	0x0a, 0x0b, 0x66, 0x6f, 0x74, 0x6f, 0x5f, 0x62, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x6f, 0x74, 0x6f, 0x42, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x12,
	0x14, 0x0a, 0x05, 0x68, 0x61, 0x72, 0x67, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x68, 0x61, 0x72, 0x67, 0x61, 0x12, 0x23, 0x0a, 0x0d, 0x6e, 0x61, 0x6d, 0x61, 0x5f, 0x6d, 0x61,
	0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x61,
	0x6d, 0x61, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x22, 0x16, 0x0a, 0x14, 0x52, 0x65,
	0x61, 0x64, 0x57, 0x69, 0x74, 0x68, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x4e, 0x0a, 0x15, 0x52, 0x65, 0x61, 0x64, 0x57, 0x69, 0x74, 0x68, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x09, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x63, 0x72, 0x75, 0x64, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x65,
	0x61, 0x64, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x73, 0x22, 0x8c, 0x01, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52,
	0x65, 0x61, 0x64, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x61, 0x6d, 0x61,
	0x5f, 0x62, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e,
	0x61, 0x6d, 0x61, 0x42, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x6f, 0x74,
	0x6f, 0x5f, 0x62, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x66, 0x6f, 0x74, 0x6f, 0x42, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x61,
	0x72, 0x67, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x68, 0x61, 0x72, 0x67, 0x61,
	0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x6f, 0x6d, 0x6f, 0x72, 0x5f, 0x62, 0x61, 0x74, 0x63, 0x68, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x6f, 0x6d, 0x6f, 0x72, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x22, 0x1d, 0x0a, 0x1b, 0x52, 0x65, 0x61, 0x64, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x64, 0x42, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x5a, 0x0a, 0x1c, 0x52, 0x65, 0x61, 0x64, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x64, 0x42, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3a, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x72, 0x75, 0x64, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x65, 0x61, 0x64, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65,
	0x64, 0x52, 0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x22, 0x8f, 0x01, 0x0a,
	0x16, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x61, 0x64, 0x4e, 0x6f, 0x74,
	0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x61, 0x6d, 0x61, 0x5f,
	0x62, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x61,
	0x6d, 0x61, 0x42, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x6f, 0x6d, 0x6f,
	0x72, 0x5f, 0x62, 0x61, 0x74, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e,
	0x6f, 0x6d, 0x6f, 0x72, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x6f,
	0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x74, 0x6f, 0x6b, 0x12, 0x1f, 0x0a,
	0x0b, 0x74, 0x67, 0x6c, 0x5f, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x74, 0x67, 0x6c, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x22, 0x1a,
	0x0a, 0x18, 0x52, 0x65, 0x61, 0x64, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x42, 0x61, 0x72,
	0x61, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x54, 0x0a, 0x19, 0x52, 0x65,
	0x61, 0x64, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x42, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x72, 0x75,
	0x64, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x61, 0x64, 0x45, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x64, 0x52, 0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73,
	0x22, 0x8c, 0x01, 0x0a, 0x13, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x61,
	0x64, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x61, 0x6d, 0x61,
	0x5f, 0x62, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e,
	0x61, 0x6d, 0x61, 0x42, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x6f, 0x6d,
	0x6f, 0x72, 0x5f, 0x62, 0x61, 0x74, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x6e, 0x6f, 0x6d, 0x6f, 0x72, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74,
	0x6f, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x74, 0x6f, 0x6b, 0x12, 0x1f,
	0x0a, 0x0b, 0x74, 0x67, 0x6c, 0x5f, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x67, 0x6c, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x22,
	0x50, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x61, 0x72, 0x67, 0x61, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x61,
	0x72, 0x67, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x68, 0x61, 0x72, 0x67, 0x61,
	0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x6f, 0x6d, 0x6f, 0x72, 0x5f, 0x62, 0x61, 0x74, 0x63, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x6f, 0x6d, 0x6f, 0x72, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x22, 0x4e, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x61, 0x72, 0x67, 0x61,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x3f, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x6c, 0x6b, 0x52,
	0x65, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x72, 0x75, 0x64, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x6c, 0x6b, 0x52, 0x65, 0x66, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x4b, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x6c, 0x6b,
	0x52, 0x65, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x76, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x6c, 0x6b, 0x52, 0x65, 0x66,
	0x12, 0x1b, 0x0a, 0x09, 0x69, 0x64, 0x5f, 0x62, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x64, 0x42, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x74, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x74, 0x6f,
	0x6b, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x78, 0x70, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x78, 0x70, 0x44, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x6e, 0x6f, 0x5f, 0x62, 0x61, 0x74, 0x63, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6e, 0x6f, 0x42, 0x61, 0x74, 0x63, 0x68, 0x32, 0x86, 0x06, 0x0a, 0x0b, 0x43, 0x72, 0x75, 0x64,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x12, 0x13, 0x2e, 0x63, 0x72, 0x75, 0x64, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x63, 0x72, 0x75, 0x64, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x07,
	0x52, 0x65, 0x61, 0x64, 0x41, 0x6c, 0x6c, 0x12, 0x14, 0x2e, 0x63, 0x72, 0x75, 0x64, 0x2e, 0x52,
	0x65, 0x61, 0x64, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e,
	0x63, 0x72, 0x75, 0x64, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x10, 0x52, 0x65, 0x61, 0x64, 0x57, 0x69, 0x74, 0x68,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x1d, 0x2e, 0x63, 0x72, 0x75, 0x64, 0x2e,
	0x52, 0x65, 0x61, 0x64, 0x57, 0x69, 0x74, 0x68, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x63, 0x72, 0x75, 0x64, 0x2e, 0x52,
	0x65, 0x61, 0x64, 0x57, 0x69, 0x74, 0x68, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0d, 0x52, 0x65, 0x61, 0x64, 0x57,
	0x69, 0x74, 0x68, 0x4a, 0x65, 0x6e, 0x69, 0x73, 0x12, 0x1a, 0x2e, 0x63, 0x72, 0x75, 0x64, 0x2e,
	0x52, 0x65, 0x61, 0x64, 0x57, 0x69, 0x74, 0x68, 0x4a, 0x65, 0x6e, 0x69, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x63, 0x72, 0x75, 0x64, 0x2e, 0x52, 0x65, 0x61, 0x64,
	0x57, 0x69, 0x74, 0x68, 0x4a, 0x65, 0x6e, 0x69, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x51, 0x0a, 0x10, 0x52, 0x65, 0x61, 0x64, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x61, 0x74,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x1d, 0x2e, 0x63, 0x72, 0x75, 0x64, 0x2e, 0x52, 0x65, 0x61,
	0x64, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x63, 0x72, 0x75, 0x64, 0x2e, 0x52, 0x65, 0x61, 0x64,
	0x57, 0x69, 0x74, 0x68, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0d, 0x52, 0x65, 0x61, 0x64, 0x57, 0x69, 0x74, 0x68,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1a, 0x2e, 0x63, 0x72, 0x75, 0x64, 0x2e, 0x52, 0x65, 0x61,
	0x64, 0x57, 0x69, 0x74, 0x68, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x63, 0x72, 0x75, 0x64, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x57, 0x69, 0x74,
	0x68, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x54,
	0x0a, 0x11, 0x52, 0x65, 0x61, 0x64, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x42, 0x61, 0x72,
	0x61, 0x6e, 0x67, 0x12, 0x1e, 0x2e, 0x63, 0x72, 0x75, 0x64, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x45,
	0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x42, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x63, 0x72, 0x75, 0x64, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x45,
	0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x42, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x14, 0x52, 0x65, 0x61, 0x64, 0x4e, 0x6f, 0x74, 0x45,
	0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x42, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x12, 0x21, 0x2e, 0x63,
	0x72, 0x75, 0x64, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x64, 0x42, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x22, 0x2e, 0x63, 0x72, 0x75, 0x64, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x4e, 0x6f, 0x74, 0x45, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x64, 0x42, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x61, 0x72,
	0x67, 0x61, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1d, 0x2e, 0x63, 0x72, 0x75, 0x64, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x61, 0x72, 0x67, 0x61, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x63, 0x72, 0x75, 0x64, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x48, 0x61, 0x72, 0x67, 0x61, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x42, 0x75, 0x6c, 0x6b, 0x52, 0x65, 0x66, 0x12, 0x1a, 0x2e, 0x63, 0x72, 0x75, 0x64, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x6c, 0x6b, 0x52, 0x65, 0x66, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x63, 0x72, 0x75, 0x64, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x42, 0x75, 0x6c, 0x6b, 0x52, 0x65, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x0c, 0x5a, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x72, 0x75, 0x64, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_service_proto_rawDescOnce sync.Once
	file_proto_service_proto_rawDescData = file_proto_service_proto_rawDesc
)

func file_proto_service_proto_rawDescGZIP() []byte {
	file_proto_service_proto_rawDescOnce.Do(func() {
		file_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_service_proto_rawDescData)
	})
	return file_proto_service_proto_rawDescData
}

var file_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_proto_service_proto_goTypes = []interface{}{
	(*CreateRequest)(nil),                // 0: crud.CreateRequest
	(*CreateResponse)(nil),               // 1: crud.CreateResponse
	(*ReadAllRequest)(nil),               // 2: crud.ReadAllRequest
	(*ReadAllResponse)(nil),              // 3: crud.ReadAllResponse
	(*ResponseRead)(nil),                 // 4: crud.ResponseRead
	(*ReadWithCategoryRequest)(nil),      // 5: crud.ReadWithCategoryRequest
	(*ReadWithCategoryResponse)(nil),     // 6: crud.ReadWithCategoryResponse
	(*ResponseReadCategory)(nil),         // 7: crud.ResponseReadCategory
	(*ReadWithJenisRequest)(nil),         // 8: crud.ReadWithJenisRequest
	(*ReadWithJenisResponse)(nil),        // 9: crud.ReadWithJenisResponse
	(*ResponseReadJenis)(nil),            // 10: crud.ResponseReadJenis
	(*ReadWithMaterialRequest)(nil),      // 11: crud.ReadWithMaterialRequest
	(*ReadWithMaterialResponse)(nil),     // 12: crud.ReadWithMaterialResponse
	(*ResponseReadMaterial)(nil),         // 13: crud.ResponseReadMaterial
	(*ReadWithBatchRequest)(nil),         // 14: crud.ReadWithBatchRequest
	(*ReadWithBatchResponse)(nil),        // 15: crud.ReadWithBatchResponse
	(*ResponseReadBatch)(nil),            // 16: crud.ResponseReadBatch
	(*ReadNotExpiredBarangRequest)(nil),  // 17: crud.ReadNotExpiredBarangRequest
	(*ReadNotExpiredBarangResponse)(nil), // 18: crud.ReadNotExpiredBarangResponse
	(*ResponseReadNotExpired)(nil),       // 19: crud.ResponseReadNotExpired
	(*ReadExpiredBarangRequest)(nil),     // 20: crud.ReadExpiredBarangRequest
	(*ReadExpiredBarangResponse)(nil),    // 21: crud.ReadExpiredBarangResponse
	(*ResponseReadExpired)(nil),          // 22: crud.ResponseReadExpired
	(*UpdateHargaBatchRequest)(nil),      // 23: crud.UpdateHargaBatchRequest
	(*UpdateHargaBatchResponse)(nil),     // 24: crud.UpdateHargaBatchResponse
	(*CreateBulkRefRequest)(nil),         // 25: crud.CreateBulkRefRequest
	(*CreateBulkRefResponse)(nil),        // 26: crud.CreateBulkRefResponse
	(*CreateBulkRef)(nil),                // 27: crud.CreateBulkRef
}
var file_proto_service_proto_depIdxs = []int32{
	4,  // 0: crud.ReadAllResponse.responses:type_name -> crud.ResponseRead
	7,  // 1: crud.ReadWithCategoryResponse.responses:type_name -> crud.ResponseReadCategory
	10, // 2: crud.ReadWithJenisResponse.responses:type_name -> crud.ResponseReadJenis
	13, // 3: crud.ReadWithMaterialResponse.responses:type_name -> crud.ResponseReadMaterial
	16, // 4: crud.ReadWithBatchResponse.responses:type_name -> crud.ResponseReadBatch
	19, // 5: crud.ReadNotExpiredBarangResponse.responses:type_name -> crud.ResponseReadNotExpired
	22, // 6: crud.ReadExpiredBarangResponse.responses:type_name -> crud.ResponseReadExpired
	27, // 7: crud.CreateBulkRefRequest.data:type_name -> crud.CreateBulkRef
	0,  // 8: crud.CrudService.Create:input_type -> crud.CreateRequest
	2,  // 9: crud.CrudService.ReadAll:input_type -> crud.ReadAllRequest
	5,  // 10: crud.CrudService.ReadWithCategory:input_type -> crud.ReadWithCategoryRequest
	8,  // 11: crud.CrudService.ReadWithJenis:input_type -> crud.ReadWithJenisRequest
	11, // 12: crud.CrudService.ReadWithMaterial:input_type -> crud.ReadWithMaterialRequest
	14, // 13: crud.CrudService.ReadWithBatch:input_type -> crud.ReadWithBatchRequest
	20, // 14: crud.CrudService.ReadExpiredBarang:input_type -> crud.ReadExpiredBarangRequest
	17, // 15: crud.CrudService.ReadNotExpiredBarang:input_type -> crud.ReadNotExpiredBarangRequest
	23, // 16: crud.CrudService.UpdateHargaBatch:input_type -> crud.UpdateHargaBatchRequest
	25, // 17: crud.CrudService.CreateBulkRef:input_type -> crud.CreateBulkRefRequest
	1,  // 18: crud.CrudService.Create:output_type -> crud.CreateResponse
	3,  // 19: crud.CrudService.ReadAll:output_type -> crud.ReadAllResponse
	6,  // 20: crud.CrudService.ReadWithCategory:output_type -> crud.ReadWithCategoryResponse
	9,  // 21: crud.CrudService.ReadWithJenis:output_type -> crud.ReadWithJenisResponse
	12, // 22: crud.CrudService.ReadWithMaterial:output_type -> crud.ReadWithMaterialResponse
	15, // 23: crud.CrudService.ReadWithBatch:output_type -> crud.ReadWithBatchResponse
	21, // 24: crud.CrudService.ReadExpiredBarang:output_type -> crud.ReadExpiredBarangResponse
	18, // 25: crud.CrudService.ReadNotExpiredBarang:output_type -> crud.ReadNotExpiredBarangResponse
	24, // 26: crud.CrudService.UpdateHargaBatch:output_type -> crud.UpdateHargaBatchResponse
	26, // 27: crud.CrudService.CreateBulkRef:output_type -> crud.CreateBulkRefResponse
	18, // [18:28] is the sub-list for method output_type
	8,  // [8:18] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_service_proto_init() }
func file_proto_service_proto_init() {
	if File_proto_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseRead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadWithCategoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadWithCategoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseReadCategory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadWithJenisRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadWithJenisResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseReadJenis); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadWithMaterialRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadWithMaterialResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseReadMaterial); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadWithBatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadWithBatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseReadBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadNotExpiredBarangRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadNotExpiredBarangResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseReadNotExpired); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadExpiredBarangRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadExpiredBarangResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseReadExpired); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateHargaBatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateHargaBatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBulkRefRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBulkRefResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBulkRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_service_proto_goTypes,
		DependencyIndexes: file_proto_service_proto_depIdxs,
		MessageInfos:      file_proto_service_proto_msgTypes,
	}.Build()
	File_proto_service_proto = out.File
	file_proto_service_proto_rawDesc = nil
	file_proto_service_proto_goTypes = nil
	file_proto_service_proto_depIdxs = nil
}
